import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';

export const blueprintCommand = new Command('blueprint')
  .description('Generate BLUEPRINT.md and dare-dag.yaml from DESIGN.md')
  .argument('[design-file]', 'Path to DESIGN.md', 'DARE/DESIGN.md')
  .action(async (designFile: string) => {
    console.log(chalk.blue.bold('\n🏗️  DARE Framework - Blueprint Phase\n'));

    const dareDir = path.resolve(process.cwd(), 'DARE');
    const designPath = path.resolve(process.cwd(), designFile);

    if (!await fs.pathExists(designPath)) {
      console.error(chalk.red(`❌ DESIGN.md not found at ${designPath}`));
      console.log(chalk.yellow('Run: dare design "Your project description"'));
      process.exit(1);
    }

    await fs.ensureDir(dareDir);

    // Generate BLUEPRINT.md
    const blueprintContent = `# BLUEPRINT

## Architecture Overview
> Generated from DESIGN.md

## Technology Stack
- **Backend:** To be defined
- **Frontend:** To be defined
- **Database:** To be defined
- **Infrastructure:** To be defined

## Modules
### Module 1: Core
- Description
- Endpoints
- Data models

## API Contracts
\`\`\`yaml
openapi: 3.0.0
info:
  title: Project API
  version: 0.1.0
\`\`\`

## Database Schema
\`\`\`sql
-- Tables to be defined
\`\`\`

---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;

    // Generate dare-dag.yaml (DAG Task Runner)
    const dagContent = `title: "Project - Development Tasks"
version: "1.0.0"
generated: "${new Date().toISOString()}"

models:
  HIGH: "gpt-4"
  MED: "gpt-4o-mini"
  LOW: "gpt-4o-mini"

tasks:
  - id: task-001
    title: "Setup project structure"
    depends_on: []
    complexity: LOW
    subtask_prompt: |
      Setup the base project structure following the BLUEPRINT.md specifications.
      Create all necessary directories, configuration files, and base dependencies.

  - id: task-002
    title: "Implement database schema"
    depends_on: []
    complexity: MED
    subtask_prompt: |
      Implement the database schema as defined in BLUEPRINT.md.
      Create migrations, models, and seed data.

  - id: task-003
    title: "Implement core API endpoints"
    depends_on: [task-001, task-002]
    complexity: HIGH
    subtask_prompt: |
      Implement the core API endpoints as defined in BLUEPRINT.md.
      Follow the API contracts and ensure proper error handling.

  - id: task-004
    title: "Implement authentication"
    depends_on: [task-001, task-002]
    complexity: HIGH
    subtask_prompt: |
      Implement authentication and authorization following security best practices.

  - id: task-005
    title: "Write tests"
    depends_on: [task-003, task-004]
    complexity: MED
    subtask_prompt: |
      Write unit and integration tests for all implemented features.
      Ensure at least 80% code coverage.
`;

    // Generate TASKS.md
    const tasksContent = `# TASKS

## Status Legend
- ⏳ PENDING
- 🔄 IN_PROGRESS
- ✅ DONE
- ❌ FAILED
- ⏭️  SKIPPED

## Tasks

| ID | Title | Status | Depends On | Complexity |
|----|-------|--------|------------|------------|
| task-001 | Setup project structure | ⏳ PENDING | - | LOW |
| task-002 | Implement database schema | ⏳ PENDING | - | MED |
| task-003 | Implement core API endpoints | ⏳ PENDING | task-001, task-002 | HIGH |
| task-004 | Implement authentication | ⏳ PENDING | task-001, task-002 | HIGH |
| task-005 | Write tests | ⏳ PENDING | task-003, task-004 | MED |

---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;

    await fs.writeFile(path.join(dareDir, 'BLUEPRINT.md'), blueprintContent);
    await fs.writeFile(path.join(dareDir, 'dare-dag.yaml'), dagContent);
    await fs.writeFile(path.join(dareDir, 'TASKS.md'), tasksContent);

    console.log(chalk.green('✅ Files generated:'));
    console.log(`   ${chalk.cyan('DARE/BLUEPRINT.md')} - Architecture specification`);
    console.log(`   ${chalk.cyan('DARE/dare-dag.yaml')} - Task dependency graph`);
    console.log(`   ${chalk.cyan('DARE/TASKS.md')} - Task tracking\n`);
    console.log(chalk.cyan('Next: dare execute --parallel\n'));
  });
