import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';

export const designCommand = new Command('design')
  .description('Generate a DESIGN.md from a project description')
  .argument('<description>', 'Project description')
  .action(async (description: string) => {
    console.log(chalk.blue.bold('\n📐 DARE Framework - Design Phase\n'));

    const dareDir = path.resolve(process.cwd(), 'DARE');
    await fs.ensureDir(dareDir);

    const designContent = `# DESIGN

## Project Description
${description}

## Goals
- [ ] Define core requirements
- [ ] Identify stakeholders
- [ ] Map user journeys

## Constraints
- [ ] Technical constraints
- [ ] Business constraints
- [ ] Timeline constraints

## Success Criteria
- [ ] Define measurable outcomes

---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;

    const designPath = path.join(dareDir, 'DESIGN.md');
    await fs.writeFile(designPath, designContent);

    console.log(chalk.green(`✅ DESIGN.md created at ${designPath}`));
    console.log(chalk.cyan('\nNext: dare blueprint\n'));
  });
