import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import type { DnaFacts } from '../utils/dna-detector.js';
import type { PatternsFacts } from '../utils/pattern-detector.js';
import {
  buildDesignQuestionnaire,
  renderDesignQuestionnaireBlock,
} from '../utils/design-questionnaire.js';
import { addAiOptions, aiOptionsFromFlags } from '../ai/command-options.js';
import type { AiCommandOptions } from '../ai/types.js';
import { maybeRunAiEnrichment } from '../ai/pipeline.js';

function staticDesignContent(description: string): string {
  return `# DESIGN

## Project Description
${description}

## Goals
- [ ] Define core requirements
- [ ] Identify stakeholders
- [ ] Map user journeys

## Constraints
- [ ] Technical constraints
- [ ] Business constraints
- [ ] Timeline constraints

## Success Criteria
- [ ] Define measurable outcomes

---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;
}

export const designCommand = new Command('design')
  .description('Generate a DESIGN.md from a project description')
  .argument('<description>', 'Project description')
  .option(
    '--interactive',
    'Emit deterministic planning questionnaire from dna/patterns facts (no LLM)',
  );

addAiOptions(designCommand);

designCommand.action(async (description: string, opts: { interactive?: boolean } & AiCommandOptions) => {
    console.log(chalk.blue.bold('\n📐 DARE Framework - Design Phase\n'));

    const dareDir = path.resolve(process.cwd(), 'DARE');
    await fs.ensureDir(dareDir);

    let designContent: string;

    if (opts.interactive) {
      const dnaPath = path.join(dareDir, 'dna-facts.json');
      const patternsPath = path.join(dareDir, 'patterns-facts.json');
      const dna: DnaFacts | null = (await fs.pathExists(dnaPath))
        ? ((await fs.readJson(dnaPath)) as DnaFacts)
        : null;
      const patterns: PatternsFacts | null = (await fs.pathExists(patternsPath))
        ? ((await fs.readJson(patternsPath)) as PatternsFacts)
        : null;

      const artifact = buildDesignQuestionnaire(dna, patterns);
      const questionnaireBlock = renderDesignQuestionnaireBlock(artifact);

      console.log(chalk.cyan(questionnaireBlock));
      console.log('');

      designContent = `# DESIGN

## Project Description
${description}

${questionnaireBlock}---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;
    } else {
      designContent = staticDesignContent(description);
    }

    const designPath = path.join(dareDir, 'DESIGN.md');
    await fs.writeFile(designPath, designContent);

    const dnaPath = path.join(dareDir, 'dna-facts.json');
    const patternsPath = path.join(dareDir, 'patterns-facts.json');
    const aiFacts = {
      description,
      dna: (await fs.pathExists(dnaPath)) ? await fs.readJson(dnaPath) : null,
      patterns: (await fs.pathExists(patternsPath)) ? await fs.readJson(patternsPath) : null,
    };
    const aiOpts = aiOptionsFromFlags(opts);
    await maybeRunAiEnrichment({
      enabled: aiOpts.enabled,
      provider: aiOpts.provider,
      json: aiOpts.json,
      command: 'design',
      cwd: process.cwd(),
      facts: aiFacts,
    });

    console.log(chalk.green(`✅ DESIGN.md created at ${designPath}`));
    console.log(chalk.cyan('\nNext: dare blueprint\n'));
  });
