/**
 * dare-quality-telemetry — report formatters
 * Formats ProjectMetricReport into ASCII table, JSON, and PR comment markdown.
 * License: MIT
 */

import { ProjectMetricReport, RegressionResult } from './types.js';

const PASS_ICON = '✅';
const FAIL_ICON = '❌';

/**
 * Formats a ProjectMetricReport as an ASCII table.
 *
 * Example output:
 * ┌─────────────────────────┬───────┬────────────────────────────────────────────────────┐
 * │ Skill / Metric          │ Pass  │ Details                                            │
 * ├─────────────────────────┼───────┼────────────────────────────────────────────────────┤
 * │ dare-ax / M-01          │  ✅   │ All 5 required sections present in llms.txt        │
 * ...
 */
export function formatTable(report: ProjectMetricReport): string {
  const COL1 = 30;
  const COL2 = 7;
  const COL3 = 52;

  const hr = `├${'─'.repeat(COL1 + 2)}┼${'─'.repeat(COL2 + 2)}┼${'─'.repeat(COL3 + 2)}┤`;
  const top = `┌${'─'.repeat(COL1 + 2)}┬${'─'.repeat(COL2 + 2)}┬${'─'.repeat(COL3 + 2)}┐`;
  const bot = `└${'─'.repeat(COL1 + 2)}┴${'─'.repeat(COL2 + 2)}┴${'─'.repeat(COL3 + 2)}┘`;

  const pad = (str: string, width: number) =>
    str.length >= width ? str.slice(0, width) : str + ' '.repeat(width - str.length);

  const row = (c1: string, c2: string, c3: string) =>
    `│ ${pad(c1, COL1)} │ ${pad(c2, COL2)} │ ${pad(c3, COL3)} │`;

  const lines: string[] = [];
  lines.push(top);
  lines.push(row('Skill / Metric', 'Pass', 'Details'));

  for (const skillReport of report.skills) {
    lines.push(hr);
    for (const metric of skillReport.metrics) {
      const label = `${skillReport.skillName} / ${metric.id}`;
      const icon = metric.pass ? PASS_ICON : FAIL_ICON;
      const details = metric.details || metric.description;
      lines.push(row(label, icon, details));
    }
  }

  lines.push(hr);
  lines.push(
    row(
      'OVERALL',
      report.overall.allPass ? PASS_ICON : FAIL_ICON,
      `${report.overall.score} metrics passed — commit: ${report.commit}`
    )
  );
  lines.push(bot);

  return lines.join('\n');
}

/**
 * Formats a ProjectMetricReport as pretty-printed JSON.
 */
export function formatJSON(report: ProjectMetricReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Formats a ProjectMetricReport as a GitHub PR comment in Markdown.
 *
 * Includes regression warnings if regressions are provided.
 */
export function formatPRComment(
  report: ProjectMetricReport,
  regressions: RegressionResult[] = []
): string {
  const overallIcon = report.overall.allPass ? PASS_ICON : FAIL_ICON;
  const overallStatus = report.overall.allPass ? 'All metrics passing' : 'Some metrics failing';

  const lines: string[] = [
    `## DARE Quality Metrics ${overallIcon}`,
    '',
    `**Status:** ${overallStatus} — **${report.overall.score}** metrics passed`,
    `**Commit:** \`${report.commit}\``,
    `**Timestamp:** ${report.timestamp}`,
    '',
  ];

  // Skill-by-skill breakdown
  for (const skillReport of report.skills) {
    const skillIcon = skillReport.summary.allPass ? PASS_ICON : FAIL_ICON;
    lines.push(`### ${skillIcon} ${skillReport.skillName} (${skillReport.summary.score})`);
    lines.push('');
    lines.push('| Metric | Status | Details |');
    lines.push('|--------|--------|---------|');

    for (const metric of skillReport.metrics) {
      const icon = metric.pass ? PASS_ICON : FAIL_ICON;
      const details = (metric.details || metric.description).replace(/\|/g, '\\|');
      lines.push(`| ${metric.id} | ${icon} | ${details} |`);
    }
    lines.push('');
  }

  // Regression warnings
  if (regressions.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`### ⚠️ Regressions Detected (${regressions.length})`);
    lines.push('');
    lines.push('The following metrics regressed compared to the baseline:');
    lines.push('');
    lines.push('| Skill | Metric | Baseline | Current |');
    lines.push('|-------|--------|----------|---------|');

    for (const r of regressions) {
      lines.push(
        `| ${r.skill} | ${r.metricId} | ${r.baseline ? PASS_ICON : FAIL_ICON} | ${r.current ? PASS_ICON : FAIL_ICON} |`
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [dare-quality-telemetry](https://github.com/dewtech-technologies/dare-method)*');

  return lines.join('\n');
}
