apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-dare-landing-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dare.dewtech.tech
      secretName: dare-landing-tls
  rules:
    - host: dare.dewtech.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-dare-landing
                port:
                  number: 80
