apiVersion: v1
kind: Service
metadata:
  name: ui-dare-landing
  namespace: apps
  labels:
    app: ui-dare-landing
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ui-dare-landing
