import fs from 'fs-extra';
import path from 'path';
import type { DnaFacts } from '../../utils/dna-detector.js';
import type { PatternsFacts } from '../../utils/pattern-detector.js';
import {
  buildDesignQuestionnaire,
  renderDesignQuestionnaireBlock,
} from '../../utils/design-questionnaire.js';
import { runCommandEnrichment } from '../../ai/pipeline.js';
import { registerRunner, type CommandRunOptions, type CommandRunResult } from './types.js';

function staticDesignContent(description: string): string {
  return `# DESIGN

## Project Description
${description}

## Goals
- [ ] Define core requirements
- [ ] Identify stakeholders
- [ ] Map user journeys

## Constraints
- [ ] Technical constraints
- [ ] Business constraints
- [ ] Timeline constraints

## Success Criteria
- [ ] Define measurable outcomes

---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;
}

function parseDescription(input: Record<string, unknown> | undefined): string | null {
  const raw = input?.description;
  if (typeof raw !== 'string') return null;
  const description = raw.trim();
  return description.length > 0 ? description : null;
}

function parseInteractive(input: Record<string, unknown> | undefined): boolean {
  const raw = input?.interactive;
  if (typeof raw === 'boolean') return raw;
  if (typeof raw === 'string') return raw.toLowerCase() === 'true';
  return false;
}

async function readJsonIfExists<T>(filePath: string): Promise<T | null> {
  if (!(await fs.pathExists(filePath))) return null;
  return (await fs.readJson(filePath)) as T;
}

export async function runDesign(opts: CommandRunOptions): Promise<CommandRunResult> {
  const description = parseDescription(opts.input);
  if (!description) {
    return {
      command: 'design',
      ok: false,
      facts: { input: opts.input ?? {} },
      artifacts: [],
      error: 'input.description is required',
    };
  }

  const interactive = parseInteractive(opts.input);
  const dareDir = path.resolve(opts.cwd, 'DARE');
  await fs.ensureDir(dareDir);

  const dnaPath = path.join(dareDir, 'dna-facts.json');
  const patternsPath = path.join(dareDir, 'patterns-facts.json');
  const dna = await readJsonIfExists<DnaFacts>(dnaPath);
  const patterns = await readJsonIfExists<PatternsFacts>(patternsPath);

  let questionnaireBlock: string | null = null;
  const designContent = interactive
    ? (() => {
        const artifact = buildDesignQuestionnaire(dna, patterns);
        questionnaireBlock = renderDesignQuestionnaireBlock(artifact);
        return `# DESIGN

## Project Description
${description}

${questionnaireBlock}---
*Generated by DARE Framework - ${new Date().toISOString()}*
`;
      })()
    : staticDesignContent(description);

  const designPath = path.join(dareDir, 'DESIGN.md');
  await fs.writeFile(designPath, designContent);

  const artifacts: string[] = ['DARE/DESIGN.md'];
  const facts: Record<string, unknown> = {
    description,
    interactive,
    dna,
    patterns,
  };
  if (questionnaireBlock) {
    facts.questionnaireBlock = questionnaireBlock;
  }

  if (!opts.ai) {
    return {
      command: 'design',
      ok: true,
      facts,
      artifacts,
      summary: questionnaireBlock ? [questionnaireBlock] : undefined,
    };
  }

  const enrichment = await runCommandEnrichment({
    command: 'design',
    cwd: opts.cwd,
    provider: opts.provider,
    deep: opts.deep,
    facts,
  });

  if (enrichment.artifactPath) {
    artifacts.push(path.relative(opts.cwd, enrichment.artifactPath).replace(/\\/g, '/'));
  }

  if (!enrichment.ok) {
    return {
      command: 'design',
      ok: false,
      facts,
      artifacts,
      enrichment,
      summary: questionnaireBlock ? [questionnaireBlock] : undefined,
      error: enrichment.error ?? 'AI enrichment failed',
    };
  }

  return {
    command: 'design',
    ok: true,
    facts,
    artifacts,
    enrichment,
    summary: questionnaireBlock ? [questionnaireBlock] : undefined,
  };
}

registerRunner('design', runDesign);
